services:
  shipitron:
    build: .
    image: 786715713882.dkr.ecr.us-east-1.amazonaws.com/shipitron:dev
    environment:
      FIXUID:
      FIXGID:
    volumes:
      - bundler-data:/usr/local/bundle
      - ~/dev/app:/app # Set this to the application to be shipitron'd
      - shipitron-home:/home/shipitron
      - ~/.config/shipitron:/home/shipitron/.config/shipitron
      - .:/shipitron

  util:
    build:
      context: .
      dockerfile: Dockerfile.util
    image: 786715713882.dkr.ecr.us-east-1.amazonaws.com/shipitron:util

  staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: public.ecr.aws/a5k7g6j4/shipitron:staging

  s3:
    image: 786715713882.dkr.ecr.us-east-1.amazonaws.com/cloudserver:latest
    environment:
      REMOTE_MANAGEMENT_DISABLE: 1
      ENDPOINT: s3.test
      LISTEN_ADDR: 0.0.0.0
      VIRTUAL_HOST: .s3.test
      VIRTUAL_PORT: 8000
      HTTPS_METHOD: noredirect
      SERVICE_8000_NAME: s3
    extra_hosts:
      - "s3.test:127.0.0.1"
    ports:
      - '8000'
    volumes:
      - s3-data:/usr/src/app/localData
      - s3-metadata:/usr/src/app/localMetadata

  specs:
    build: .
    image: 786715713882.dkr.ecr.us-east-1.amazonaws.com/shipitron:dev
    command: rspec
    environment:
      FIXUID:
      FIXGID:
      BUILDKITE:
      BUILDKITE_BUILD_URL:
      BUILDKITE_JOB_ID:
      BUILDKITE_AGENT_ACCESS_TOKEN:
    working_dir: /shipitron
    volumes:
      - bundler-data:/usr/local/bundle
      - shipitron-home:/home/shipitron
      - .:/shipitron

  release_gem:
    image: 786715713882.dkr.ecr.us-east-1.amazonaws.com/shipitron:dev
    command: rake release
    working_dir: /shipitron
    environment:
      FIXUID:
      FIXGID:
    volumes:
      - bundler-data:/usr/local/bundle
      - shipitron-home:/home/shipitron
      - .:/shipitron
      - ~/.dotfiles/gitconfig:/root/.gitconfig
      - ~/.dotfiles/gitconfig.user:/root/.gitconfig.user
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.gem:/root/.gem

volumes:
  shipitron-home:
  bundler-data:
  s3-data:
  s3-metadata:
